// 各种下拉框数据
// 飞机号
export const acrNumList = [
  'B304H',
  'B6396',
  'B20AJ',
  'B32EC',
  'B30EQ',
  'B9957',
  'B326J',
  'B6395',
  'B30EP',
  'B32D9',
  'B9978',
  'B1681',
  'B325L',
  'B6670',
  'B320Z',
  'B1647',
  'B324C',
  'B324D',
  'B32CJ',
  'B1857',
  'B1006',
  'B327W',
  'B6736',
  'B8957',
  'B6787',
  'B209R',
  'B6949',
  'B8536',
  'B321A',
  'B8537',
  'B1870',
  'B6667',
  'B6666',
  'B8407',
  'B1646',
  'B8955',
  'B32DF',
  'B6921',
  'B324V',
  'B327D',
  'B6735',
  'B1001',
  'B6788',
  'B324U',
  'B6948',
  'B321C',
  'B8956',
  'B323D',
  'B8458',
  'B6717',
  'B8459',
  'B8457',
  'B6618',
  'B6963',
  'B6572',
  'B1808',
  'B20D1',
  'B6338',
  'B8540',
  'B8317',
  'B1872',
  'B6341',
  'B8315',
  'B7777',
  'B323R',
  'B30C9',
  'B6381',
  'B304G',
  'B7779',
  'B326H',
  'B30FC',
  'B7778',
  'B32EH',
  'B8236',
  'B6768',
  'B6861',
  'B6619',
  'B1871',
  'B6962',
  'B-652G',
  'B20DT',
  'B8538',
  'B1645',
  'B8539',
  'B8036',
  'B6901',
  'B6602',
  'B6966',
  'B1115',
  'B6668',
  'B6860',
  'B6640',
  'B8888',
  'B1005',
  'B6922',
  'B30CT',
  'B1003',
  'B8035',
  'B1002',
  'B8235',
  'B-656E',
  'B8408',
  'B6340',
  'B6965',
  'B8587',
  'B207N',
  'B30FQ',
  'B322E',
  'B8068',
  'B32EJ',
  'B208A',
]

// 机场
export const airportList = [
  {
    aptIata: 'VIE',
    aptIcao: 'LOWW',
    aptNameCn: '维也纳',
    aptNameFs: '维',
  },
  {
    aptIata: 'SJW',
    aptIcao: 'ZBSJ',
    aptNameCn: '正定',
    aptNameFs: '石',
  },
  {
    aptIata: 'WGN',
    aptIcao: 'ZGSY',
    aptNameCn: '武冈',
    aptNameFs: '邵',
  },
  {
    aptIata: 'BKK',
    aptIcao: 'VTBS',
    aptNameCn: '素万那普',
    aptNameFs: '曼',
  },
  {
    aptIata: 'YCU',
    aptIcao: 'ZBYC',
    aptNameCn: '盐湖',
    aptNameFs: '解',
  },
  {
    aptIata: 'CGD',
    aptIcao: 'ZGCD',
    aptNameCn: '桃花源',
    aptNameFs: '德',
  },
  {
    aptIata: 'YGJ',
    aptIcao: 'RJOH',
    aptNameCn: '鬼太郎',
    aptNameFs: '子',
  },
  {
    aptIata: 'MIG',
    aptIcao: 'ZUMY',
    aptNameCn: '南郊',
    aptNameFs: '绵',
  },
  {
    aptIata: 'YIH',
    aptIcao: 'ZHYC',
    aptNameCn: '三峡',
    aptNameFs: '宜',
  },
  {
    aptIata: 'HUZ',
    aptIcao: 'ZGHZ',
    aptNameCn: '平潭',
    aptNameFs: '惠',
  },
  {
    aptIata: 'KWE',
    aptIcao: 'ZUGY',
    aptNameCn: '龙洞堡',
    aptNameFs: '筑',
  },
  {
    aptIata: 'LCX',
    aptIcao: 'ZSLO',
    aptNameCn: '冠豸山',
    aptNameFs: '豸',
  },
  {
    aptIata: 'KHH',
    aptIcao: 'RCKH',
    aptNameCn: '高雄',
    aptNameFs: '雄',
  },
  {
    aptIata: 'KIX',
    aptIcao: 'RJBB',
    aptNameCn: '关西',
    aptNameFs: '阪',
  },
  {
    aptIata: 'MAN',
    aptIcao: 'EGCC',
    aptNameCn: '曼彻斯特',
    aptNameFs: '彻',
  },
  {
    aptIata: 'KBV',
    aptIcao: 'VTSG',
    aptNameCn: '甲米',
    aptNameFs: '甲',
  },
  {
    aptIata: 'INC',
    aptIcao: 'ZLIC',
    aptNameCn: '河东',
    aptNameFs: '银',
  },
  {
    aptIata: 'MZG',
    aptIcao: 'RCQC',
    aptNameCn: '澎湖',
    aptNameFs: '澎',
  },
  {
    aptIata: 'TNA',
    aptIcao: 'ZSJN',
    aptNameCn: '遥墙',
    aptNameFs: '济',
  },
  {
    aptIata: 'DLC',
    aptIcao: 'ZYTL',
    aptNameCn: '周水子',
    aptNameFs: '连',
  },
  {
    aptIata: 'HIA',
    aptIcao: 'ZSSH',
    aptNameCn: '涟水',
    aptNameFs: '淮',
  },
  {
    aptIata: 'HND',
    aptIcao: 'RJTT',
    aptNameCn: '羽田',
    aptNameFs: '羽',
  },
  {
    aptIata: 'SHE',
    aptIcao: 'ZYTX',
    aptNameCn: '桃仙',
    aptNameFs: '沈',
  },
  {
    aptIata: 'TPE',
    aptIcao: 'RCTP',
    aptNameCn: '桃园',
    aptNameFs: '台',
  },
  {
    aptIata: 'DQA',
    aptIcao: 'ZYDQ',
    aptNameCn: '萨尔图',
    aptNameFs: '庆',
  },
  {
    aptIata: 'NGB',
    aptIcao: 'ZSNB',
    aptNameCn: '栎社',
    aptNameFs: '甬',
  },
  {
    aptIata: 'ZHY',
    aptIcao: 'ZLZW',
    aptNameCn: '沙坡头',
    aptNameFs: '卫',
  },
  {
    aptIata: 'VVO',
    aptIcao: 'UHWW',
    aptNameCn: '海参崴',
    aptNameFs: '崴',
  },
  {
    aptIata: 'YNJ',
    aptIcao: 'ZYYJ',
    aptNameCn: '朝阳川',
    aptNameFs: '延',
  },
  {
    aptIata: 'LYG',
    aptIcao: 'ZSLG',
    aptNameCn: '花果山',
    aptNameFs: '果',
  },
  {
    aptIata: 'YNZ',
    aptIcao: 'ZSYN',
    aptNameCn: '南洋',
    aptNameFs: '盐',
  },
  {
    aptIata: 'DOY',
    aptIcao: 'ZSDY',
    aptNameCn: '胜利',
    aptNameFs: '营',
  },
  {
    aptIata: 'JED',
    aptIcao: 'OEJN',
    aptNameCn: '吉达',
    aptNameFs: '级',
  },
  {
    aptIata: 'SHA',
    aptIcao: 'ZSSS',
    aptNameCn: '虹桥',
    aptNameFs: '虹',
  },
  {
    aptIata: 'YTY',
    aptIcao: 'ZSYA',
    aptNameCn: '泰州',
    aptNameFs: '扬',
  },
  {
    aptIata: 'YSQ',
    aptIcao: 'ZYSQ',
    aptNameCn: '查干湖',
    aptNameFs: '松',
  },
  {
    aptIata: 'CDG',
    aptIcao: 'LFPG',
    aptNameCn: '戴高乐',
    aptNameFs: '戴',
  },
  {
    aptIata: 'YKH',
    aptIcao: 'ZYYK',
    aptNameCn: '兰旗',
    aptNameFs: '旗',
  },
  {
    aptIata: 'NKG',
    aptIcao: 'ZSNJ',
    aptNameCn: '禄口',
    aptNameFs: '宁',
  },
  {
    aptIata: 'YNT',
    aptIcao: 'ZSYT',
    aptNameCn: '蓬莱',
    aptNameFs: '烟',
  },
  {
    aptIata: 'CIF',
    aptIcao: 'ZBCF',
    aptNameCn: '玉龙',
    aptNameFs: '赤',
  },
  {
    aptIata: 'CGK',
    aptIcao: 'WIII',
    aptNameCn: '雅加达',
    aptNameFs: '雅',
  },
  {
    aptIata: 'WUX',
    aptIcao: 'ZSWX',
    aptNameCn: '硕放',
    aptNameFs: '锡',
  },
  {
    aptIata: 'JUH',
    aptIcao: 'ZSJH',
    aptNameCn: '九华山',
    aptNameFs: '池',
  },
  {
    aptIata: 'UYN',
    aptIcao: 'ZLYL',
    aptNameCn: '榆阳',
    aptNameFs: '榆',
  },
  {
    aptIata: 'DNH',
    aptIcao: 'ZLDH',
    aptNameCn: '莫高',
    aptNameFs: '敦',
  },
  {
    aptIata: 'LBV',
    aptIcao: 'FOOL',
    aptNameCn: '加蓬',
    aptNameFs: '蓬',
  },
  {
    aptIata: 'GYU',
    aptIcao: 'ZLGY',
    aptNameCn: '六盘山',
    aptNameFs: '固',
  },
  {
    aptIata: 'LJG',
    aptIcao: 'ZPLJ',
    aptNameCn: '三义',
    aptNameFs: '丽',
  },
  {
    aptIata: 'VCA',
    aptIcao: 'VVCT',
    aptNameCn: '芹苴',
    aptNameFs: '芹',
  },
  {
    aptIata: 'PEN',
    aptIcao: 'WMKP',
    aptNameCn: '槟城',
    aptNameFs: '槟',
  },
  {
    aptIata: 'KOS',
    aptIcao: 'VDSV',
    aptNameCn: '西哈努克',
    aptNameFs: '努',
  },
  {
    aptIata: 'KWL',
    aptIcao: 'ZGKL',
    aptNameCn: '两江',
    aptNameFs: '桂',
  },
  {
    aptIata: 'SWA',
    aptIcao: 'ZGOW',
    aptNameCn: '潮汕',
    aptNameFs: '揭',
  },
  {
    aptIata: 'KNH',
    aptIcao: 'RCBS',
    aptNameCn: '金门/上义',
    aptNameFs: null,
  },
  {
    aptIata: 'WUA',
    aptIcao: 'ZBUH',
    aptNameCn: '乌海',
    aptNameFs: '狮',
  },
  {
    aptIata: 'BFJ',
    aptIcao: 'ZUBJ',
    aptNameCn: '飞雄',
    aptNameFs: '毕',
  },
  {
    aptIata: 'JGN',
    aptIcao: 'ZLJQ',
    aptNameCn: '酒泉',
    aptNameFs: '嘉',
  },
  {
    aptIata: 'AOG',
    aptIcao: 'ZYAS',
    aptNameCn: '腾鳌',
    aptNameFs: '鞍',
  },
  {
    aptIata: 'YYA',
    aptIcao: 'ZGYY',
    aptNameCn: '三荷',
    aptNameFs: '荷',
  },
  {
    aptIata: 'XIY',
    aptIcao: 'ZLXY',
    aptNameCn: '咸阳',
    aptNameFs: '陕',
  },
  {
    aptIata: 'DMK',
    aptIcao: 'VTBD',
    aptNameCn: '廊曼',
    aptNameFs: '廊',
  },
  {
    aptIata: 'LLF',
    aptIcao: 'ZGLG',
    aptNameCn: '零陵',
    aptNameFs: '永',
  },
  {
    aptIata: 'BUD',
    aptIcao: 'LHBP',
    aptNameCn: '布达佩斯',
    aptNameFs: '佩',
  },
  {
    aptIata: 'HRB',
    aptIcao: 'ZYHB',
    aptNameCn: '太平',
    aptNameFs: '哈',
  },
  {
    aptIata: 'AEB',
    aptIcao: 'ZGBS',
    aptNameCn: '巴马',
    aptNameFs: '百',
  },
  {
    aptIata: 'WUH',
    aptIcao: 'ZHHH',
    aptNameCn: '天河',
    aptNameFs: '武',
  },
  {
    aptIata: 'NGO',
    aptIcao: 'RJGG',
    aptNameCn: '中部',
    aptNameFs: '名',
  },
  {
    aptIata: 'BTS',
    aptIcao: 'LZIB',
    aptNameCn: '布拉迪斯拉发',
    aptNameFs: '斯',
  },
  {
    aptIata: 'TSN',
    aptIcao: 'ZBTJ',
    aptNameCn: '滨海',
    aptNameFs: '津',
  },
  {
    aptIata: 'LHR',
    aptIcao: 'EGLL',
    aptNameCn: '希思罗',
    aptNameFs: '熙',
  },
  {
    aptIata: 'ATH',
    aptIcao: 'LGAV',
    aptNameCn: '雅典国际机场',
    aptNameFs: '典',
  },
  {
    aptIata: 'PNH',
    aptIcao: 'VDPP',
    aptNameCn: '金边',
    aptNameFs: '边',
  },
  {
    aptIata: 'LZH',
    aptIcao: 'ZGZH',
    aptNameCn: '白莲',
    aptNameFs: '柳',
  },
  {
    aptIata: 'VCS',
    aptIcao: 'VVCS',
    aptNameCn: null,
    aptNameFs: null,
  },
  {
    aptIata: 'KUL',
    aptIcao: 'WMKK',
    aptNameCn: '吉隆坡',
    aptNameFs: '坡',
  },
  {
    aptIata: 'HKG',
    aptIcao: 'VHHH',
    aptNameCn: '香港',
    aptNameFs: '香',
  },
  {
    aptIata: 'CNX',
    aptIcao: 'VTCC',
    aptNameCn: '清迈',
    aptNameFs: '清',
  },
  {
    aptIata: 'ICN',
    aptIcao: 'RKSI',
    aptNameCn: '仁川',
    aptNameFs: '仁',
  },
  {
    aptIata: 'RLK',
    aptIcao: 'ZBYZ',
    aptNameCn: '天吉泰',
    aptNameFs: '巴',
  },
  {
    aptIata: 'BAV',
    aptIcao: 'ZBOW',
    aptNameCn: '东河',
    aptNameFs: '包',
  },
  {
    aptIata: 'TEN',
    aptIcao: 'ZUTR',
    aptNameCn: '凤凰',
    aptNameFs: '铜',
  },
  {
    aptIata: 'PKX',
    aptIcao: 'ZBAD',
    aptNameCn: '大兴',
    aptNameFs: '兴',
  },
  {
    aptIata: 'LFQ',
    aptIcao: 'ZBLF',
    aptNameCn: '尧都',
    aptNameFs: '临',
  },
  {
    aptIata: 'HAM',
    aptIcao: 'EDDH',
    aptNameCn: '汉堡',
    aptNameFs: '汉',
  },
  {
    aptIata: 'LNL',
    aptIcao: 'ZLLN',
    aptNameCn: '成县',
    aptNameFs: '陇',
  },
  {
    aptIata: 'PRG',
    aptIcao: 'LKPR',
    aptNameCn: '布拉格',
    aptNameFs: '步',
  },
  {
    aptIata: 'MNL',
    aptIcao: 'RPLL',
    aptNameCn: '马尼拉',
    aptNameFs: '马',
  },
  {
    aptIata: 'FOC',
    aptIcao: 'ZSFZ',
    aptNameCn: '长乐',
    aptNameFs: '福',
  },
  {
    aptIata: 'FUG',
    aptIcao: 'ZSFY',
    aptNameCn: '阜阳',
    aptNameFs: '阜',
  },
  {
    aptIata: 'LEJ',
    aptIcao: 'EDDP',
    aptNameCn: '莱比锡-哈雷',
    aptNameFs: '莱',
  },
  {
    aptIata: 'ACX',
    aptIcao: 'ZUYI',
    aptNameCn: '万峰林',
    aptNameFs: '义',
  },
  {
    aptIata: 'YBP',
    aptIcao: 'ZUYB',
    aptNameCn: '五粮液',
    aptNameFs: '宾',
  },
  {
    aptIata: 'HFE',
    aptIcao: 'ZSOF',
    aptNameCn: '新桥',
    aptNameFs: '皖',
  },
  {
    aptIata: 'XXX',
    aptIcao: 'XXXX',
    aptNameCn: 'XX',
    aptNameFs: null,
  },
  {
    aptIata: 'XMN',
    aptIcao: 'ZSAM',
    aptNameCn: '高崎',
    aptNameFs: '厦',
  },
  {
    aptIata: 'JJN',
    aptIcao: 'ZSQZ',
    aptNameCn: '晋江',
    aptNameFs: '泉',
  },
  {
    aptIata: 'TAO',
    aptIcao: 'ZSQD',
    aptNameCn: '胶东',
    aptNameFs: '青',
  },
  {
    aptIata: 'XFN',
    aptIcao: 'ZHXF',
    aptNameCn: '刘集',
    aptNameFs: '樊',
  },
  {
    aptIata: 'HGH',
    aptIcao: 'ZSHC',
    aptNameCn: '萧山',
    aptNameFs: '杭',
  },
  {
    aptIata: 'MDL',
    aptIcao: 'VYMD',
    aptNameCn: '曼德勒',
    aptNameFs: '漫',
  },
  {
    aptIata: 'CZX',
    aptIcao: 'ZSCG',
    aptNameCn: '奔牛',
    aptNameFs: '常',
  },
  {
    aptIata: 'RGN',
    aptIcao: 'VYYY',
    aptNameCn: '仰光',
    aptNameFs: '仰',
  },
  {
    aptIata: 'AMS',
    aptIcao: 'EHAM',
    aptNameCn: '史基浦',
    aptNameFs: '姆',
  },
  {
    aptIata: 'DLI',
    aptIcao: 'VVDL',
    aptNameCn: '莲姜',
    aptNameFs: '叻',
  },
  {
    aptIata: 'ISB',
    aptIcao: 'OPIS',
    aptNameCn: null,
    aptNameFs: null,
  },
  {
    aptIata: 'VTE',
    aptIcao: 'VLVT',
    aptNameCn: '瓦岱',
    aptNameFs: '万',
  },
  {
    aptIata: 'SIN',
    aptIcao: 'WSSS',
    aptNameCn: '樟宜',
    aptNameFs: '新',
  },
  {
    aptIata: 'MFM',
    aptIcao: 'VMMC',
    aptNameCn: '澳门',
    aptNameFs: '澳',
  },
  {
    aptIata: 'NNY',
    aptIcao: 'ZHNY',
    aptNameCn: '姜营',
    aptNameFs: '宛',
  },
  {
    aptIata: 'CJU',
    aptIcao: 'RKPC',
    aptNameCn: '济州',
    aptNameFs: '州',
  },
  {
    aptIata: 'CGO',
    aptIcao: 'ZHCC',
    aptNameCn: '新郑',
    aptNameFs: '郑',
  },
  {
    aptIata: 'NRT',
    aptIcao: 'RJAA',
    aptNameCn: '成田',
    aptNameFs: '田',
  },
  {
    aptIata: 'HLD',
    aptIcao: 'ZBLA',
    aptNameCn: '海拉尔',
    aptNameFs: '海',
  },
  {
    aptIata: 'FRA',
    aptIcao: 'EDDF',
    aptNameCn: '美茵',
    aptNameFs: '法',
  },
  {
    aptIata: 'TFU',
    aptIcao: 'ZUTF',
    aptNameCn: '天府',
    aptNameFs: '府',
  },
  {
    aptIata: 'LYA',
    aptIcao: 'ZHLY',
    aptNameCn: '洛阳',
    aptNameFs: '洛',
  },
  {
    aptIata: 'HCZ',
    aptIcao: 'ZGCZ',
    aptNameCn: '北湖',
    aptNameFs: '郴',
  },
  {
    aptIata: 'HAK',
    aptIcao: 'ZJHK',
    aptNameCn: '美兰',
    aptNameFs: '琼',
  },
  {
    aptIata: 'TYN',
    aptIcao: 'ZBYN',
    aptNameCn: '武宿',
    aptNameFs: '并',
  },
  {
    aptIata: 'LLV',
    aptIcao: 'ZBLL',
    aptNameCn: '大武',
    aptNameFs: '吕',
  },
  {
    aptIata: 'HLH',
    aptIcao: 'ZBUL',
    aptNameCn: '义勒力特',
    aptNameFs: '依',
  },
  {
    aptIata: 'BZX',
    aptIcao: 'ZUBZ',
    aptNameCn: '恩阳',
    aptNameFs: '川',
  },
  {
    aptIata: 'SGN',
    aptIcao: 'VVTS',
    aptNameCn: '新山一',
    aptNameFs: '胡',
  },
  {
    aptIata: 'DAT',
    aptIcao: 'ZBDT',
    aptNameCn: '云冈',
    aptNameFs: '云',
  },
  {
    aptIata: 'DUB',
    aptIcao: 'EIDW',
    aptNameCn: '都柏林',
    aptNameFs: '柏',
  },
  {
    aptIata: 'NZH',
    aptIcao: 'ZBMZ',
    aptNameCn: '西郊',
    aptNameFs: '满',
  },
  {
    aptIata: 'JHG',
    aptIcao: 'ZPJH',
    aptNameCn: '嘎洒',
    aptNameFs: '纳',
  },
  {
    aptIata: 'HZG',
    aptIcao: 'ZLHZ',
    aptNameCn: '城固',
    aptNameFs: '城',
  },
  {
    aptIata: 'STN',
    aptIcao: 'EGSS',
    aptNameCn: '斯坦斯特德',
    aptNameFs: '伦',
  },
  {
    aptIata: 'JIC',
    aptIcao: 'ZLJC',
    aptNameCn: '金川',
    aptNameFs: '金',
  },
  {
    aptIata: 'PEK',
    aptIcao: 'ZBAA',
    aptNameCn: '首都',
    aptNameFs: '京',
  },
  {
    aptIata: 'FCO',
    aptIcao: 'LIRF',
    aptNameCn: '菲乌米奇诺',
    aptNameFs: '菲',
  },
  {
    aptIata: 'NQZ',
    aptIcao: 'UACC',
    aptNameCn: '阿斯塔纳',
    aptNameFs: null,
  },
  {
    aptIata: 'CAN',
    aptIcao: 'ZGGG',
    aptNameCn: '白云',
    aptNameFs: '穗',
  },
  {
    aptIata: 'ZHA',
    aptIcao: 'ZGZJ',
    aptNameCn: '吴川',
    aptNameFs: '湛',
  },
  {
    aptIata: 'MAD',
    aptIcao: 'LEMD',
    aptNameCn: '马德里巴拉哈斯',
    aptNameFs: '理',
  },
  {
    aptIata: 'NBS',
    aptIcao: 'ZYBS',
    aptNameCn: '长白山',
    aptNameFs: '白',
  },
  {
    aptIata: 'XNN',
    aptIcao: 'ZLXN',
    aptNameCn: '曹家堡',
    aptNameFs: '西',
  },
  {
    aptIata: 'HET',
    aptIcao: 'ZBHH',
    aptNameCn: '白塔',
    aptNameFs: '呼',
  },
  {
    aptIata: 'BKI',
    aptIcao: 'WBKK',
    aptNameCn: '沙巴',
    aptNameFs: '沙',
  },
  {
    aptIata: 'CKG',
    aptIcao: 'ZUCK',
    aptNameCn: '江北',
    aptNameFs: '渝',
  },
  {
    aptIata: 'WUT',
    aptIcao: 'ZBXZ',
    aptNameCn: '五台山',
    aptNameFs: '忻',
  },
  {
    aptIata: 'URC',
    aptIcao: 'ZWWW',
    aptNameCn: '地窝堡',
    aptNameFs: '乌',
  },
  {
    aptIata: 'NNG',
    aptIcao: 'ZGNN',
    aptNameCn: '吴圩',
    aptNameFs: '邕',
  },
  {
    aptIata: 'WMT',
    aptIcao: 'ZUMT',
    aptNameCn: '茅台',
    aptNameFs: '茅',
  },
  {
    aptIata: 'CSX',
    aptIcao: 'ZGHA',
    aptNameCn: '黄花',
    aptNameFs: '湘',
  },
  {
    aptIata: 'XIN',
    aptIcao: 'ZGXN',
    aptNameCn: null,
    aptNameFs: null,
  },
  {
    aptIata: 'KLO',
    aptIcao: 'RPVK',
    aptNameCn: '卡利博',
    aptNameFs: '卡',
  },
  {
    aptIata: 'HAN',
    aptIcao: 'VVNB',
    aptNameCn: '内拜',
    aptNameFs: '河',
  },
  {
    aptIata: 'JIU',
    aptIcao: 'ZSJJ',
    aptNameCn: '庐山',
    aptNameFs: '九',
  },
  {
    aptIata: 'WNZ',
    aptIcao: 'ZSWZ',
    aptNameCn: '龙湾',
    aptNameFs: '温',
  },
  {
    aptIata: 'CGQ',
    aptIcao: 'ZYCC',
    aptNameCn: '龙嘉',
    aptNameFs: '春',
  },
  {
    aptIata: 'SQJ',
    aptIcao: 'ZSSM',
    aptNameCn: '沙县',
    aptNameFs: '虬',
  },
  {
    aptIata: 'NTG',
    aptIcao: 'ZSNT',
    aptNameCn: '兴东',
    aptNameFs: '通',
  },
  {
    aptIata: 'HKT',
    aptIcao: 'VTSP',
    aptNameCn: '普吉',
    aptNameFs: '普',
  },
  {
    aptIata: 'TGO',
    aptIcao: 'ZBTL',
    aptNameCn: '通辽',
    aptNameFs: '辽',
  },
  {
    aptIata: 'CTU',
    aptIcao: 'ZUUU',
    aptNameCn: '双流',
    aptNameFs: '蓉',
  },
  {
    aptIata: 'CTS',
    aptIcao: 'RJCC',
    aptNameCn: '新千岁',
    aptNameFs: null,
  },
  {
    aptIata: 'BHY',
    aptIcao: 'ZGBH',
    aptNameCn: '福成',
    aptNameFs: '北',
  },
  {
    aptIata: 'CIH',
    aptIcao: 'ZBCZ',
    aptNameCn: '王村',
    aptNameFs: '治',
  },
  {
    aptIata: 'HEL',
    aptIcao: 'EFHK',
    aptNameCn: '万塔',
    aptNameFs: '赫',
  },
  {
    aptIata: 'KHN',
    aptIcao: 'ZSCN',
    aptNameCn: '昌北',
    aptNameFs: '南',
  },
  {
    aptIata: 'XFW',
    aptIcao: 'EDHI',
    aptNameCn: '芬肯韦德',
    aptNameFs: '芬',
  },
  {
    aptIata: 'OTP',
    aptIcao: 'LROP',
    aptNameCn: '亨利科安德',
    aptNameFs: '亨',
  },
  {
    aptIata: 'KMG',
    aptIcao: 'ZPPP',
    aptNameCn: '长水',
    aptNameFs: '昆',
  },
  {
    aptIata: 'CEB',
    aptIcao: 'RPVM',
    aptNameCn: '麦克坦-宿务',
    aptNameFs: '宿',
  },
  {
    aptIata: 'LPF',
    aptIcao: 'ZUPS',
    aptNameCn: '月照',
    aptNameFs: '六',
  },
  {
    aptIata: 'HPH',
    aptIcao: 'VVCI',
    aptNameCn: '吉碑',
    aptNameFs: '防',
  },
  {
    aptIata: 'HSC',
    aptIcao: 'ZGSG',
    aptNameCn: '丹霞',
    aptNameFs: '韶',
  },
  {
    aptIata: 'MXP',
    aptIcao: 'LIMC',
    aptNameCn: '米兰马尔本萨',
    aptNameFs: '萨',
  },
  {
    aptIata: 'LZO',
    aptIcao: 'ZULZ',
    aptNameCn: '云龙',
    aptNameFs: '泸',
  },
  {
    aptIata: 'OKA',
    aptIcao: 'ROAH',
    aptNameCn: '那霸',
    aptNameFs: '霸',
  },
  {
    aptIata: 'LGW',
    aptIcao: 'EGKK',
    aptNameCn: '盖特威克',
    aptNameFs: '盖',
  },
  {
    aptIata: 'ZUH',
    aptIcao: 'ZGSD',
    aptNameCn: '金湾',
    aptNameFs: '珠',
  },
  {
    aptIata: 'SZX',
    aptIcao: 'ZGSZ',
    aptNameCn: '宝安',
    aptNameFs: '圳',
  },
  {
    aptIata: 'SYX',
    aptIcao: 'ZJSY',
    aptNameCn: '凤凰',
    aptNameFs: '崖',
  },
  {
    aptIata: 'GYS',
    aptIcao: 'ZUGU',
    aptNameCn: '盘龙',
    aptNameFs: '元',
  },
  {
    aptIata: 'WDS',
    aptIcao: 'ZHSY',
    aptNameCn: '武当山',
    aptNameFs: '堰',
  },
  {
    aptIata: 'DYG',
    aptIcao: 'ZGDY',
    aptNameCn: '荷花',
    aptNameFs: '庸',
  },
  {
    aptIata: 'HNY',
    aptIcao: 'ZGHY',
    aptNameCn: '南岳',
    aptNameFs: '衡',
  },
  {
    aptIata: 'BAR',
    aptIcao: 'ZJQH',
    aptNameCn: '博鳌',
    aptNameFs: '鳌',
  },
  {
    aptIata: 'LHW',
    aptIcao: 'ZLLL',
    aptNameCn: '中川',
    aptNameFs: '兰',
  },
  {
    aptIata: 'KOW',
    aptIcao: 'ZSGZ',
    aptNameCn: '黄金',
    aptNameFs: '赣',
  },
  {
    aptIata: 'YZY',
    aptIcao: 'ZLZY',
    aptNameCn: '甘州',
    aptNameFs: '掖',
  },
  {
    aptIata: 'PVG',
    aptIcao: 'ZSPD',
    aptNameCn: '浦东',
    aptNameFs: '浦',
  },
  {
    aptIata: 'WEH',
    aptIcao: 'ZSWH',
    aptNameCn: '大水泊',
    aptNameFs: '威',
  },
]
